spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pdshared?serverTimezone=Asia/Seoul
    username: root
    password: 1q2w3e4r
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 500MB
      max-request-size: 515MB
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
file:
  dir: C:/test/
  security:
    user:
      name: user
      password: test


jwt:
  secret: sdjfijweoinfkadsifvjewrjgniosdjggiawekjfsmiozdkljmviaeoskdlfmv

