spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pdshared?serverTimezone=Asia/Seoul
    username: root
    password: 1q2w3e4r

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  security:
    user:
      name: user
      password: test


